spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password:
    driverClassName: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
